[tools]
precommit = "latest"

[env]
DATABASE_URL = "postgres://postgres:postgres@localhost/postgres"
DJANGO_SETTINGS_MODULE = "[[project_name]].config.settings.test"
SECRET_KEY = "!!!! Change me !!!!"
