#!/usr/bin/env bash

# Reset
export COLOR_RESET='\033[0m'

# Regular Colors
export COLOR_BLACK='\033[0;30m'
export COLOR_RED='\033[0;31m'
export COLOR_GREEN='\033[0;32m'
export COLOR_YELLOW='\033[0;33m'
export COLOR_BLUE='\033[0;34m'
export COLOR_PURPLE='\033[0;35m'
export COLOR_CYAN='\033[0;36m'
export COLOR_WHITE='\033[0;37m'

# Bold Colors
export COLOR_BOLD_BLACK='\033[1;30m'
export COLOR_BOLD_RED='\033[1;31m'
export COLOR_BOLD_GREEN='\033[1;32m'
export COLOR_BOLD_YELLOW='\033[1;33m'
export COLOR_BOLD_BLUE='\033[1;34m'
export COLOR_BOLD_PURPLE='\033[1;35m'
export COLOR_BOLD_CYAN='\033[1;36m'
export COLOR_BOLD_WHITE='\033[1;37m'

# Utility functions
color_echo() {
  local color="$1"
  shift
  echo -e "${color}$*${COLOR_RESET}"
}

color_error() {
  color_echo "$COLOR_RED" "$@" >&2
}

color_warning() {
  color_echo "$COLOR_YELLOW" "$@"
}

color_success() {
  color_echo "$COLOR_GREEN" "$@"
}

color_info() {
  color_echo "$COLOR_CYAN" "$@"
}
