repos:
  ## system
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.3
    hooks:
        - id: pyupgrade
          args: [--py311-plus]
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.12.0
    hooks:
        - id: django-upgrade
          args: [--target-version, "4.1"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
        - id: check-yaml
        #    -   id: end-of-file-fixer
        #    -   id: trailing-whitespace
        - id: debug-statements
        - id: mixed-line-ending
  - repo: https://github.com/pycqa/doc8
    rev: v1.0.0
    hooks:
        - id: doc8

  #python
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        exclude: .*migrations/.*
        name: black
        types: [python]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.259'
    hooks:
      - id: ruff
        args: [
                --fix,
                --exit-non-zero-on-fix,
              ]

  # TODO:  https://github.com/adamchainz/pre-commit-oxipng


  - repo: local
    hooks:
      - id: stylelint
        name: stylelint
        entry: npx stylelint
        language: node
        files: ^{{cookiecutter.repo_name}}/static_source/
        types_or: [css, scss]
        args: [--report-needless-disables, --report-invalid-scope-disables, --fix, --allow-empty-input]

      - id: eslint
        name: eslint
        entry: npx eslint
        language: node
        files: ^{{cookiecutter.repo_name}}/static_source/
        types_or: [javascript, ts]
        args: [--fix]

      - id: tsc
        name: tsc
        entry: npx tsc --noEmit
        files: ^{{cookiecutter.repo_name}}/static_source/
        language: system
        types_or: [javascript, ts]
        pass_filenames: false
